# Site settings
title: Christopher Hoo Chi Yang's Portfolio Page
description: A portfolio page for Christopher Hoo Chi Yang
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://www.linkedin.com/in/christopher-chi-yang-hoo-570698bb/ # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: cyh002
user_description: Data Scientist in Singapore with a passion for AI and Machine Learning, and a background in Economics and Social Sciences. Past experience in Semiconductor Industry, Market Research, and Data Analytics. Huge IT enthusiast and a lifelong learner.
user_title: AI Engineer 
user_country: Singapore
email: c-hi.yang@hotmail.sg

linkedin: https://www.linkedin.com/in/christopher-chi-yang-hoo-570698bb/
github_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
